[workspace]
members = [
    "light-client-lib",
    "light-client-bin",
    "light-client-wasm",
    "./wasm/light-client-db-worker",
    "./wasm/light-client-db-common",
]

resolver = "2"


[profile.release]
overflow-checks = true
