[workspace]
members = [
    "light-client-lib",
    # "light-client-bin",
    "light-client-wasm",
    "light-client-db-worker",
    "light-client-db-common",
]
exclude = ["light-client-bin"]

resolver = "2"


[profile.release]
overflow-checks = true
