[package]
name = "light-client-db-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
idb = "0.6"
web-sys = "0.3.72"
anyhow = "1.0.93"
bincode = "1.3.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.45"
